CREATE TABLE contactsData(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, -- ADD THIS ID SO IT CREATE A UNIQUE ID FOR EACH DRINKS
name VARCHAR(16), 
phoneNumber VARCHAR(20), 
address VARCHAR(20), 
email VARCHAR(20) );